// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrudWrkK8S-XBkFRdHzodLZDyWu1FOSo',
    appId: '1:685112436333:web:9c6c09de0e7bd1af3a8164',
    messagingSenderId: '685112436333',
    projectId: 'scheduleme-application',
    authDomain: 'scheduleme-application.firebaseapp.com',
    storageBucket: 'scheduleme-application.appspot.com',
    measurementId: 'G-BEKFRLP68L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWR5SyYK79odF8ZxDHrQGrxKr19UsNTZU',
    appId: '1:685112436333:android:7f4649411efc5e7d3a8164',
    messagingSenderId: '685112436333',
    projectId: 'scheduleme-application',
    storageBucket: 'scheduleme-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChjCjDBB6AUrOG_lyDaS3MLP4aMeCOezw',
    appId: '1:685112436333:ios:39dce9132cb6b8563a8164',
    messagingSenderId: '685112436333',
    projectId: 'scheduleme-application',
    storageBucket: 'scheduleme-application.appspot.com',
    iosClientId: '685112436333-mj16sn8vnr1bgom5nk1cc8semhpuui4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedulemeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChjCjDBB6AUrOG_lyDaS3MLP4aMeCOezw',
    appId: '1:685112436333:ios:39dce9132cb6b8563a8164',
    messagingSenderId: '685112436333',
    projectId: 'scheduleme-application',
    storageBucket: 'scheduleme-application.appspot.com',
    iosClientId: '685112436333-mj16sn8vnr1bgom5nk1cc8semhpuui4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.schedulemeApplication',
  );
}
